<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\query\CategoryPostQuery;

/**
 * This is the base-model class for table "category_post".
 *
 * @property integer $category_id
 * @property string $category_name
 *
 * @property \app\models\Post[] $posts
 */
abstract class CategoryPost extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category_post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['category_name'], 'string', 'max' => 255],
            [['category_name'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'category_id' => 'Category ID',
            'category_name' => 'Category Name',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosts()
    {
        return $this->hasMany(\app\models\Post::class, ['category_id' => 'category_id']);
    }

    /**
     * @inheritdoc
     * @return CategoryPostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CategoryPostQuery(static::class);
    }
}
