<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\query\OrderQuery;

/**
 * This is the base-model class for table "order".
 *
 * @property integer $id
 * @property integer $user_id
 * @property double $total
 * @property string $order_date
 * @property integer $status
 * @property string $deleted_at
 * @property integer $payment_method
 * @property integer $payment_status
 * @property string $app_trans_id
 * @property string $zp_trans_id
 * @property string $m_refund_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\OrderItem[] $orderItems
 * @property \app\models\User $user
 */
abstract class Order extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['user_id', 'status', 'payment_method', 'payment_status'], 'integer'],
            [['total'], 'number'],
            [['order_date', 'deleted_at'], 'safe'],
            [['app_trans_id', 'zp_trans_id', 'm_refund_id'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['user_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'user_id' => 'User ID',
            'total' => 'Total',
            'order_date' => 'Order Date',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'payment_method' => 'Payment Method',
            'payment_status' => 'Payment Status',
            'app_trans_id' => 'App Trans ID',
            'zp_trans_id' => 'Zp Trans ID',
            'm_refund_id' => 'M Refund ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems()
    {
        return $this->hasMany(\app\models\OrderItem::class, ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user_id']);
    }

    /**
     * @inheritdoc
     * @return OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new OrderQuery(static::class);
    }
}
