<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\query\ProductQuery;

/**
 * This is the base-model class for table "product".
 *
 * @property integer $id
 * @property string $product_name
 * @property double $price
 * @property string $description
 * @property string $image
 * @property integer $stock
 * @property integer $status
 * @property integer $category_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\CategoryProduct $category
 * @property \app\models\OrderDetail[] $orderDetails
 * @property \app\models\ProductImage[] $productImages
 */
abstract class Product extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['product_name', 'price'], 'required'],
            [['price'], 'number'],
            [['description', 'image'], 'string'],
            [['stock', 'status', 'category_id'], 'integer'],
            [['product_name'], 'string', 'max' => 255],
            [['product_name'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoryProduct::class, 'targetAttribute' => ['category_id' => 'category_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'product_name' => 'Product Name',
            'price' => 'Price',
            'description' => 'Description',
            'image' => 'Image',
            'stock' => 'Stock',
            'status' => 'Status',
            'category_id' => 'Category ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\app\models\CategoryProduct::class, ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderDetails()
    {
        return $this->hasMany(\app\models\OrderDetail::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductImages()
    {
        return $this->hasMany(\app\models\ProductImage::class, ['product_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(static::class);
    }
}
